### ISSUE TITLE
PHP Fatal error:  Declaration of Symfony\Component\Cache\Traits\RedisCluster6Proxy

### ISSUE THREAD

**Issue by ruudk** [olvlvl/composer-attribute-collector#4] opened 2023-01-09 09:04 UTC
The plugin seems to trip while scanning `Symfony\Component\Cache\Traits\RedisCluster6Proxy`.

```
// snip
Found attribute Symfony\Component\Console\Attribute\AsCommand on Symfony\Component\Translation\Command\TranslationPullCommand
Found attribute Symfony\Component\Console\Attribute\AsCommand on Symfony\Component\Translation\Command\TranslationPushCommand
Found attribute Symfony\Component\Console\Attribute\AsCommand on Symfony\Component\Translation\Command\XliffLintCommand
Found attribute Symfony\Component\Console\Attribute\AsCommand on Symfony\Component\PasswordHasher\Command\UserPasswordHashCommand
Found attribute Symfony\Component\Console\Attribute\AsCommand on Symfony\Component\Form\Command\DebugCommand
Found attribute Symfony\Component\Console\Attribute\AsCommand on Symfony\Component\Dotenv\Command\DebugCommand
Found attribute Symfony\Component\DependencyInjection\Attribute\Autoconfigure on Symfony\Component\Dotenv\Command\DotenvDumpCommand
Found attribute Symfony\Component\Console\Attribute\AsCommand on Symfony\Component\Dotenv\Command\DotenvDumpCommand
PHP Fatal error:  Declaration of Symfony\Component\Cache\Traits\RedisCluster6Proxy::append($key, $value): RedisCluster|int|bool must be compatible with RedisCluster::append(string $key, mixed $value): int|bool in /Volumes/CS/www/cosmos/vendor/symfony/cache/Traits/RedisCluster6Proxy.php on line 92

Fatal error: Declaration of Symfony\Component\Cache\Traits\RedisCluster6Proxy::append($key, $value): RedisCluster|int|bool must be compatible with RedisCluster::append(string $key, mixed $value): int|bool in /Volumes/CS/www/cosmos/vendor/symfony/cache/Traits/RedisCluster6Proxy.php on line 92
```

Using `symfony/cache` `v6.2.4`

**Comment by ruudk** [comment] 2023-01-09 18:24
The issue is, (and don't get me wrong) I don't care about what happens in vendor. Symfony probably ships this for a reason. It was never a problem. But this plugin scans everything and that fails.

**Comment by olvlvl** [comment] 2023-01-09 22:20
Can you share your `composer.json`? I'm capturing exceptions when classes fail to load, maybe there's another place I should fence.

**Comment by olvlvl** [comment] 2023-01-24 10:49
Hi @ruudk, I started with [a vanilla installation of Symfony 6.2](https://github.com/olvlvl/composer-attribute-collector#test-drive-with-a-symfony-app), then required `symfony/cache`. As you can see in the screen capture, the errors are captured and the faulty classes are discarded.

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/155998/214272564-47806cfb-9bab-4ef8-8d88-2940644ea75f.png">

I'm unable to reproduce the error. Please share a bit more about your setup. This is mine:

This is the `Dockerfile`:

```Dockerfile
FROM php:8.2-cli-buster

RUN echo '\
display_errors=On\n\
error_reporting=E_ALL\n\
date.timezone=UTC\n\
' >> /usr/local/etc/php/conf.d/php.ini

ENV COMPOSER_ALLOW_SUPERUSER 1

RUN apt-get update && \
	apt-get install unzip && \
	curl -s https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer | php -- --quiet && \
	mv composer.phar /usr/local/bin/composer && \
	echo 'export PATH="$HOME/.composer/vendor/bin:$PATH"\n' >> /root/.bashrc
```

This is the `docker-composer.yaml`:

```yaml
---
version: "3.2"
services:
  app:
    build: .
    volumes:
    - .:/app:delegated
    working_dir: /app
```

This is the `compose.json` file:

```json
{
  "require": {
    "php": ">=8.2",
    "slim/slim": "^4.11",
    "nyholm/psr7": "^1.5",
    "nyholm/psr7-server": "^1.0",
    "php-di/php-di": "^6.4",
    "php-di/slim-bridge": "^3.2",
    "olvlvl/composer-attribute-collector": "^1.0",
    "symfony/cache": "^6.2"
  },
  "scripts": {
    "dev": [
      "docker run -it --rm -p 80:80 -p 443:443 -v $(pwd):/app -w /app dev-build:latest"
    ],
    "dev:build": [
      "docker build -t dev-build:latest ."
    ],
    "dev:cli": [
      "docker run -it --rm -p 80:80 -p 443:443 -v $(pwd):/app -w /app --user $(id -u) dev-build:latest /bin/bash"
    ]
  },
  "require-dev": {
    "pestphp/pest": "^1.22",
    "roave/security-advisories": "dev-latest"
  },
  "config": {
    "allow-plugins": {
      "pestphp/pest-plugin": true,
      "olvlvl/composer-attribute-collector": true
    },
    "process-timeout": 0
  }
}
```

This is the resulting `attributes.php`:

```php
<?php

// attributes.php @generated by https://github.com/olvlvl/composer-attribute-collector

namespace olvlvl\ComposerAttributeCollector;

Attributes::with(fn () => new Collection(
    targetClasses: [
        \AllowDynamicProperties::class => [
            [ [], \Laravel\SerializableClosure\Support\ClosureStream::class ],
        ],

    ],
    targetMethods: [

    ],
));
```

**Comment by olvlvl** [comment] 2023-01-27 07:41
Hi, could you try this branch? https://github.com/olvlvl/composer-attribute-collector/pull/5

**Comment by ruudk** [comment] 2023-01-27 07:49
Thanks, but I already moved on. I came to see if this package was usable. Reported my findings and moved on. It's not what I'm looking for at the moment, but maybe later. Anyway, interesting project and curious to see what it will become :)

**Comment by olvlvl** [comment] 2023-01-27 10:13
Thanks for opening the issue. Fixed in https://github.com/olvlvl/composer-attribute-collector/pull/5

**Closed by olvlvl** 2023-01-27 10:13 UTC
